# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftyJsonHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftyJsonHelper

  pod ’SwiftyJSON’

  target 'SwiftyJsonHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftyJsonHelperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
